# Generated by Django 5.1.5 on 2025-01-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumerosGerados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroGerado', models.BigIntegerField(verbose_name='numeroGerado')),
                ('dataCriacao', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['dataCriacao'],
            },
        ),
    ]
