# Generated by Django 5.1.5 on 2025-01-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerosgerados',
            name='numeroGerado',
            field=models.IntegerField(verbose_name='numeroGerado'),
        ),
    ]
